### ISSUE TITLE
`Traps` appearance redesignation

### ISSUE THREAD

**Issue by CloneWith** [CloneWith/osu#7]

**Comment by NaughtyChas** [comment]
Too many colour for ban/pick, win, protect and trap will result in reading difficulties. I have asked for some feedback using our current prototype and here is a suggestion about trap display:

- **Display icons instead of using colours.**

For instance: Apply red trap on a box will result in a *subtle* flashing effect, and leave a specific icon (or text) demonstrate the status.

**Comment by NaughtyChas** [comment]
Great work on implementing trap icons into these boxes. Credit goes to @CloneWith .

Further feedback from art & design group pointed out that it would be better to have these styles of visuals:

- [ x ] Leave icons after changing the box state to `Trap`
- [ ]

**Comment by NaughtyChas** [comment]
> Great work on implementing trap icons into these boxes. Credit goes to @CloneWith .
> 
> Further feedback from art & design group pointed out that it would be better to have these styles of visuals:
> 
> * [x]  Leave icons after changing the box state to `Trap`
> * [ ]  **Add icons only without change of colour**
> 
> Second request can be resolved by adding a _very_ subtle colour to those boxes, or just simply make the colour remain unchanged after the flashing animation when a box is being picked as `Trap`.

A little bit redundancy between this issue and issue #8. More about box visuals will be traced there. Closing this issue now.
