### ISSUE TITLE
Color scheme & visuals improvement

### ISSUE THREAD

**Issue by CloneWith** [CloneWith/osu#8]
Redesign the colour scheme (or visual style) of `win`, `pick` and `ban` to make them more distinguishable.

---

Some changes must be done before we merge this branch into two currently active branches `derived/tboard` and `derived/tboard_ntcsAppend`:

- [x] Trap icons has to be coloured
- [x] Background colour change implementation method (Highest priority)
- [x] Remove trophy icons from winning boxes (won't implement)

**Comment by NaughtyChas** [comment]
commit [d69115b](https://github.com/CloneWith/osu/commit/d69115b9e000b14684b3f7b548fe32078df60057) on branch [derived/tboard_ntcsAppend](https://github.com/CloneWith/osu/compare/derived/tboard_ntcsAppend) changed visual style for box actions. **Visuals are not in its final state so further adjustment is required.**

```Csharp
                    case ChoiceType.RedWin:
                        Alpha = 1f;
                        icon.Icon = FontAwesome.Solid.Trophy;
                        icon.Colour = new OsuColour().Red;
                        icon.Alpha = 0.73f; // Added this line to distinguish last win from other wins
                        break;

                    case ChoiceType.BlueWin:
                        Alpha = 1f;
                        icon.Icon = FontAwesome.Solid.Trophy;
                        icon.Colour = new OsuColour().Blue;
                        icon.Alpha = 0.73f; // Added this line to distinguish last win from other wins
                        break;

```

---

Used `icon.Alpha = <value>;` to distinguish last win from other wins. Last win will be completely non-transparent while other wins display with a certain transparency:

![image](https://github.com/user-attachments/assets/6b72928f-aabf-472f-bfe0-e350d14743ec)

---

After talking to the art & design team, they said that now only `Trap` has to change its visual, others are in a good state now. More in [this issue]().

**Comment by NaughtyChas** [comment]
Newer design of these boxes had already been pushed onto branch `feature/BoardColor`. Some changes must be done before we merge this branch into two currently active branches `derived/tboard` and `derived/tboard_ntcsAppend`:

---

1. **Trap icons has to be coloured.**

Current design of the trap display is truely indistinguishable for red and blue:

![Left indicates Red Trap, vice versa.](https://github.com/user-attachments/assets/83d65ae1-1ab4-44c7-8fdd-19192f0c971f)

Art & Design Team has suggested to change the visual style into:

- Use **white** boundary colour
- Use **Coloured** trap icon

*Just like what we did for protect buttons, but the box boundary will not be coloured.*

Should be better in display when picked / win status have added to this box.

---

2. **Background colour change implementation method**

This should be in the 1st priority, since a protect box had a winning status added to it, the colour of the lock icon will be altered, leading more distinguishability issues.

|Red protect Red win / Blue protect Blue win|Red protect Blue win / Blue protect Red win|
|:-:|:-:|
|![image](https://github.com/user-attachments/assets/beaa0e2e-0c80-4cb2-8972-bc73e17198e0)|![image](https://github.com/user-attachments/assets/9b2623f9-b9f5-4dcf-9dee-57d26e85ec42)|

Two viable options to address this problem:

- [ ] Reshape the code to let the icons appear to be "above the colour filter layer".
- [ ] Change the background image to work as colour filter instead.
  - *If we have chosen to go with this, we might have to take the text colour into account.*

---

3. **Remove trophy icons from winning boxes**

Can't be more straight forward than that.

---

Should be something I have missed or fogotten, Add more bulletpoints below if you got more.

**Comment by NaughtyChas** [comment]
Closing this issue now.
